### ISSUE TITLE
How are you retrieving the verifier token after navigating to the authURL and authorizing access?

### ISSUE THREAD

**Issue by kaitech-corp** [srthkpthk/splitwise_api#3]
I'm receiving an Error: "Bad state: Invalid OAuth Request" even before authorizing access using the authURL.

**Comment by srthkpthk** [comment]
hi @kaitech-corp wait , i am fixing this issue , this is due to migration to null-safety

**Comment by kaitech-corp** [comment]
Got it. Thanks!

**Comment by srthkpthk** [comment]
hi @kaitech-corp can you confirm the issue is fixed

**Comment by kaitech-corp** [comment]
Unfortunately, it is not fixed. I'm receiving the same error as before:

Unhandled Exception: Bad state: Invalid OAuth Request

#0      Authorization.requestTokenCredentials (package:oauth1/src/authorization.dart:94:7)
<asynchronous suspension>
#1      SplitWiseService.validateClient (package:splitwise_api/src/util/auth/splitwise_main.dart:69:11)

In addition can you please clarify this line:
```
    //This Will print the token and also return them save them to Shared Prefs
    TokensHelper tokens = await splitWiseService.validateClient(
        verifier: 'theTokenYouGetAfterAuthorization');
```

Is retrieving the verifier token handled by your package?

**Comment by srthkpthk** [comment]
```Is retrieving the verifier token handled by your package?``` - no it prints the auth link to console , so you can open it using any package , please check the example folder you will understand it clearly @kaitech-corp

**Comment by srthkpthk** [comment]
For first timers ```var authURL = splitWiseService.validateClient();```
then open this link and copy the auth code and send it to ```    TokensHelper tokens = await splitWiseService.validateClient(
        verifier: 'here');```
then it will verify and send you tokens , save them

**Comment by kaitech-corp** [comment]
But if I do that, the way this code is written, I receive a null error for url
`if (verifier == null && tokens == null) {
      url = await _auth!.requestTemporaryCredentials('oob');
      return _auth!.getResourceOwnerAuthorizationURI(url!.credentials.token);
    } else if ((verifier != null && verifier.isNotEmpty) && tokens == null) {
      var cred =
          await _auth!.requestTokenCredentials(url!.credentials, verifier); //**This returns an error**
      print(cred.credentials);
      print(
          'Save these both to SharedPrefs or any where these are required for keep signed in ');
      _client = oauth.Client(oauth.SignatureMethods.hmacSha1,
          _clientCredentials!, cred.credentials);
      return TokensHelper(cred.credentials.token, cred.credentials.tokenSecret);`

**Comment by srthkpthk** [comment]
have you updated to latest version , because its working fine for me
